language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB_DRIVER=pdo_sqlite DB_PATH="%kernel.root_dir%/data/%database_name%.db3"
  - DB_DRIVER=pdo_mysql DB_USER=travis DB_NAME=attendee_test
  - DB_DRIVER=postgres DB_USER=postgres DB_NAME=attendee_test

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install -n
  - app/console doctrine:database:create --env=test
  - app/console doctrine:schema:create --env=test
  - app/console doctrine:fixtures:load --env=test -n

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover