language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 5.6

env:
  - DB_DRIVER=pdo_sqlite DB_PATH="%kernel.root_dir%/data/attendee_test.db3"
  - DB_DRIVER=pdo_mysql DB_USER=travis DB_NAME=attendee_test
  - DB_DRIVER=pdo_pgsql DB_USER=postgres DB_NAME=attendee_test

before_script:
  - composer self-update
  - composer install -n --prefer-source
  - app/console doctrine:database:create --env=test
  - app/console doctrine:schema:create --env=test
  - app/console doctrine:fixtures:load --env=test -n

script: phpunit --coverage-clover=coverage.clover -d zend.enable_gc=0

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
