language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install -n
  - app/console doctrine:database:create
  - app/console doctrine:schema:create
  - app/console doctrine:fixtures:load -n

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover