attendee_webpage:
    resource: "@AttendeeWebpageBundle/Controller/"
    type:     annotation
    prefix:   /

attendee_user:
    resource: "@AttendeeUserBundle/Controller/"
    type:     annotation
    prefix:   /

attendee_api:
    resource: "@AttendeeApiBundle/Controller/"
    type:     annotation
    defaults:
      _format: json
    prefix:   /api

fos_user:
    resource: "@AttendeeUserBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc